import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Cube Partner Training Program sidebar structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Training Modules',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1-foundation'
        },
        {
          type: 'autogenerated', 
          dirName: 'module-2-getting-started'
        },
        {
          type: 'autogenerated',
          dirName: 'module-3-data-modeling'
        },
        {
          type: 'autogenerated',
          dirName: 'module-4-security'
        },
        {
          type: 'autogenerated',
          dirName: 'module-5-performance'
        },
        {
          type: 'autogenerated',
          dirName: 'module-6-apis-integration'
        },
        {
          type: 'autogenerated',
          dirName: 'module-7-advanced'
        }
      ]
    },
    {
      type: 'category',
      label: 'Additional Resources',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-basics'
        },
        {
          type: 'autogenerated', 
          dirName: 'tutorial-extras'
        }
      ]
    }
  ]
};

export default sidebars;
